language: bash

services: docker

env:
  global:
    - secure: "G/CELqZR3FV2nZILJEnLlCPX+Lrw+4jZ46oyY8eloWfTIsFohs9X/WXc8eNHyh4/so72ebxD2k5DUrcj82IzSRl7SVf7dq21yXvRt5AXX/IyC5fWv8MiOJ/AJ6D4v2u2yinYovSmArmtmDNS6KyVo4xE7j+04CK2LnGzfU3DWeu05iqppgGaAW1ZUgzffSWdrG63TfCVhPJsIJwI2h90hOak0JzfacXLDb4He1C5eZsD4H9jvPSoorn9Fa3uVEP+cCj0I+sWDrslRZM8JeLCaUtGKc3c9Iyn+yCVf5aI8+RxszkDwmz9mUp/6HyebVqsDOfHLz0YqnZeOmt7Era1eH1jmKB6Y97qjsDFO/dV1dfSKk0Pil/qOAih3PigKdz1jU9aNJCt9WfdHiMmfA44j1J5wrhUxy8FTmHGDtzN9KO1Wvn2ivT/2uAWlNd2cGiEJVoQt17V9IrfwIYZ0MokXrHTrq7Iaj6XiAVlyctkHH2kChbuZw+UYB3ulTe+fGDcYTfKPcLzn1MjplcwuzzDLv091A9eVH9D3K5wvCyrdu6MxXeDQWggNIC1f8WF1nxuohXg8cyK+ZLbaOXLP18b80/Ri2cDqV8EKnvh+K6St/XwSl3nDv1VzwSioBwJyW/c4oywxd2gceMduy91iQLR4R06DcpioXoQgj2LGJmWfHQ="
    - secure: "dDVS2n45eOWr+W+APoKdM0BT/88yOjhft0UERmknpXe6eqU2HVIUAknKVkzkCeivYv8+HL/hQzKci2nE5PwVRvXSACGzL4FO6r4Vwloh4EWfDLnSZL2WGIUD4eRaLWuc4MYFloooYWjCU2qfzuevG/A+wK1Ps2zaSpY6cjQuTohT2CqvLpTICU/fX00bR0dNYjDSQhBB4B4ZTLFSBwUIS+DnOHt0hJYi+ObeuPR8Pc+njht7k4NqRP/VY38PQYjQlGLqmVDPfjwlbfCvZYQFSBTQE5TcpvJr14OQ0XaXVo/toZqcorAOjXjF/5J+S0UZF5K1x7GPWgTh0dpCQeC9HeDzfCbuuyk8EXRC19VvctH29nX8I4IFKo/JNLpdUo3Hfb+LINqIVqp6AXIR0KgIB+tr21I1t1GrM8Xp4pfBF+Kxy4I4/qH9JGIPgwZzn4v1kV/NTNwEzS51QyxOdCm2ujrLPV57++X0oi0WJzrImWoXTYjcZPy1QUrMCoalRYkcFY2HcLHPewhMoK4ztf8I+tUl61C30/sr4+D6FbuHE7WVEg9aH1R2geORZyZ2eppTsi/WU5TLXwLUf+9fOB68sdVmzqil7lLtArXlNbrnR9U1k3jFA5dp1SzyjZR0uOqP4MRsLnOVqZloaOTub4fsfqnmJMVIkgY2aP7qtemYBNw="
  matrix:
    - VERSION=5.0
    - VERSION=latest VERSION_ALIAS=5.0

before_script:
  - if [[ "$VERSION" != "latest" ]]; then cd "src/$VERSION"; fi
  - if [[ "$VERSION" == "latest" ]]; then cd "src/$VERSION_ALIAS"; fi
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
